/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Comment = IDL.Rec();
export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostType = IDL.Variant({
  'video' : IDL.Null,
  'reel' : IDL.Null,
  'image' : IDL.Null,
});
export const Ad = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'views' : IDL.Nat,
  'targetUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalMethod = IDL.Variant({
  'upi' : IDL.Text,
  'bank' : IDL.Record({ 'ifsc' : IDL.Text, 'accountNumber' : IDL.Text }),
});
export const Withdrawal = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'method' : WithdrawalMethod,
  'user' : IDL.Principal,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'totalEarnings' : IDL.Nat,
  'followers' : IDL.Vec(IDL.Principal),
  'following' : IDL.Vec(IDL.Principal),
  'profilePicture' : IDL.Opt(IDL.Text),
  'walletBalance' : IDL.Nat,
});
Comment.fill(
  IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Nat,
    'replies' : IDL.Vec(Comment),
  })
);
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'postType' : PostType,
  'shares' : IDL.Nat,
  'views' : IDL.Vec(IDL.Principal),
  'author' : IDL.Principal,
  'mediaUrl' : IDL.Text,
  'likes' : IDL.Vec(IDL.Principal),
  'saves' : IDL.Vec(IDL.Principal),
  'timestamp' : IDL.Nat,
  'caption' : IDL.Text,
  'comments' : IDL.Vec(Comment),
});
export const FriendRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const FriendRequest = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'status' : FriendRequestStatus,
  'from' : IDL.Principal,
  'timestamp' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'friendRequest' : IDL.Null,
  'follow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : NotificationType,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
  'postId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Nat], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, PostType], [IDL.Nat], []),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEarningsPaid' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalPosts' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
  'getAllWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getFeedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSuggestions' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'rejectFriendRequest' : IDL.Func([IDL.Nat], [], []),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat, WithdrawalMethod], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePost' : IDL.Func([IDL.Nat], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'sharePost' : IDL.Func([IDL.Nat], [], []),
  'trackAdView' : IDL.Func([IDL.Nat], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unsavePost' : IDL.Func([IDL.Nat], [], []),
  'updateEarningRate' : IDL.Func([IDL.Nat], [], []),
  'updateProfilePicture' : IDL.Func([IDL.Text], [], []),
  'viewPost' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Comment = IDL.Rec();
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostType = IDL.Variant({
    'video' : IDL.Null,
    'reel' : IDL.Null,
    'image' : IDL.Null,
  });
  const Ad = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'views' : IDL.Nat,
    'targetUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalMethod = IDL.Variant({
    'upi' : IDL.Text,
    'bank' : IDL.Record({ 'ifsc' : IDL.Text, 'accountNumber' : IDL.Text }),
  });
  const Withdrawal = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'method' : WithdrawalMethod,
    'user' : IDL.Principal,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'totalEarnings' : IDL.Nat,
    'followers' : IDL.Vec(IDL.Principal),
    'following' : IDL.Vec(IDL.Principal),
    'profilePicture' : IDL.Opt(IDL.Text),
    'walletBalance' : IDL.Nat,
  });
  Comment.fill(
    IDL.Record({
      'id' : IDL.Nat,
      'content' : IDL.Text,
      'author' : IDL.Principal,
      'timestamp' : IDL.Nat,
      'replies' : IDL.Vec(Comment),
    })
  );
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'postType' : PostType,
    'shares' : IDL.Nat,
    'views' : IDL.Vec(IDL.Principal),
    'author' : IDL.Principal,
    'mediaUrl' : IDL.Text,
    'likes' : IDL.Vec(IDL.Principal),
    'saves' : IDL.Vec(IDL.Principal),
    'timestamp' : IDL.Nat,
    'caption' : IDL.Text,
    'comments' : IDL.Vec(Comment),
  });
  const FriendRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const FriendRequest = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'status' : FriendRequestStatus,
    'from' : IDL.Principal,
    'timestamp' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'friendRequest' : IDL.Null,
    'follow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : NotificationType,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
    'postId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Nat], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, PostType], [IDL.Nat], []),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEarningsPaid' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalPosts' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
    'getAllWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getFeedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSuggestions' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'rejectFriendRequest' : IDL.Func([IDL.Nat], [], []),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat, WithdrawalMethod], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePost' : IDL.Func([IDL.Nat], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'sharePost' : IDL.Func([IDL.Nat], [], []),
    'trackAdView' : IDL.Func([IDL.Nat], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unsavePost' : IDL.Func([IDL.Nat], [], []),
    'updateEarningRate' : IDL.Func([IDL.Nat], [], []),
    'updateProfilePicture' : IDL.Func([IDL.Text], [], []),
    'viewPost' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };