/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ad {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'views' : bigint,
  'targetUrl' : string,
  'imageUrl' : string,
}
export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'replies' : Array<Comment>,
}
export interface FriendRequest {
  'id' : bigint,
  'to' : Principal,
  'status' : FriendRequestStatus,
  'from' : Principal,
  'timestamp' : bigint,
}
export type FriendRequestStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Notification {
  'id' : bigint,
  'notifType' : NotificationType,
  'read' : boolean,
  'recipient' : Principal,
  'sender' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'postId' : [] | [bigint],
}
export type NotificationType = { 'like' : null } |
  { 'comment' : null } |
  { 'friendRequest' : null } |
  { 'follow' : null };
export interface Post {
  'id' : bigint,
  'postType' : PostType,
  'shares' : bigint,
  'views' : Array<Principal>,
  'author' : Principal,
  'mediaUrl' : string,
  'likes' : Array<Principal>,
  'saves' : Array<Principal>,
  'timestamp' : bigint,
  'caption' : string,
  'comments' : Array<Comment>,
}
export type PostType = { 'video' : null } |
  { 'reel' : null } |
  { 'image' : null };
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'name' : string,
  'role' : UserRole,
  'totalEarnings' : bigint,
  'followers' : Array<Principal>,
  'following' : Array<Principal>,
  'profilePicture' : [] | [string],
  'walletBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Withdrawal {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'method' : WithdrawalMethod,
  'user' : Principal,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type WithdrawalMethod = { 'upi' : string } |
  { 'bank' : { 'ifsc' : string, 'accountNumber' : string } };
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[bigint], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'approveWithdrawal' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'createAd' : ActorMethod<[string, string, string], bigint>,
  'createPost' : ActorMethod<[string, string, PostType], bigint>,
  'createUserProfile' : ActorMethod<[string, string, string], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalEarningsPaid' : bigint,
      'totalUsers' : bigint,
      'totalPosts' : bigint,
    }
  >,
  'getAds' : ActorMethod<[], Array<Ad>>,
  'getAllWithdrawals' : ActorMethod<[], Array<Withdrawal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getFeedPosts' : ActorMethod<[], Array<Post>>,
  'getFriendRequests' : ActorMethod<[], Array<FriendRequest>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingWithdrawals' : ActorMethod<[], Array<Withdrawal>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getUserPosts' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSuggestions' : ActorMethod<[], Array<Principal>>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'rejectFriendRequest' : ActorMethod<[bigint], undefined>,
  'rejectWithdrawal' : ActorMethod<[bigint], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint, WithdrawalMethod], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePost' : ActorMethod<[bigint], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], bigint>,
  'sharePost' : ActorMethod<[bigint], undefined>,
  'trackAdView' : ActorMethod<[bigint], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unsavePost' : ActorMethod<[bigint], undefined>,
  'updateEarningRate' : ActorMethod<[bigint], undefined>,
  'updateProfilePicture' : ActorMethod<[string], undefined>,
  'viewPost' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];