/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Ad {
    id: bigint;
    title: string;
    active: boolean;
    views: bigint;
    targetUrl: string;
    imageUrl: string;
}
export type WithdrawalMethod = {
    __kind__: "upi";
    upi: string;
} | {
    __kind__: "bank";
    bank: {
        ifsc: string;
        accountNumber: string;
    };
};
export interface Comment {
    id: bigint;
    content: string;
    author: Principal;
    timestamp: bigint;
    replies: Array<Comment>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FriendRequest {
    id: bigint;
    to: Principal;
    status: FriendRequestStatus;
    from: Principal;
    timestamp: bigint;
}
export interface Withdrawal {
    id: bigint;
    status: WithdrawalStatus;
    method: WithdrawalMethod;
    user: Principal;
    timestamp: bigint;
    amount: bigint;
}
export interface Post {
    id: bigint;
    postType: PostType;
    shares: bigint;
    views: Array<Principal>;
    author: Principal;
    mediaUrl: string;
    likes: Array<Principal>;
    saves: Array<Principal>;
    timestamp: bigint;
    caption: string;
    comments: Array<Comment>;
}
export interface Notification {
    id: bigint;
    notifType: NotificationType;
    read: boolean;
    recipient: Principal;
    sender: Principal;
    message: string;
    timestamp: bigint;
    postId?: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    bio: string;
    username: string;
    name: string;
    role: UserRole;
    totalEarnings: bigint;
    followers: Array<Principal>;
    following: Array<Principal>;
    profilePicture?: string;
    walletBalance: bigint;
}
export enum FriendRequestStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum NotificationType {
    like = "like",
    comment = "comment",
    friendRequest = "friendRequest",
    follow = "follow"
}
export enum PostType {
    video = "video",
    reel = "reel",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptFriendRequest(requestId: bigint): Promise<void>;
    addComment(postId: bigint, content: string): Promise<bigint>;
    approveWithdrawal(withdrawalId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    banUser(user: Principal): Promise<void>;
    createAd(title: string, imageUrl: string, targetUrl: string): Promise<bigint>;
    createPost(caption: string, mediaUrl: string, postType: PostType): Promise<bigint>;
    createUserProfile(name: string, username: string, bio: string): Promise<void>;
    deletePost(postId: bigint): Promise<void>;
    followUser(userToFollow: Principal): Promise<void>;
    getAdminStats(): Promise<{
        totalEarningsPaid: bigint;
        totalUsers: bigint;
        totalPosts: bigint;
    }>;
    getAds(): Promise<Array<Ad>>;
    getAllWithdrawals(): Promise<Array<Withdrawal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getFeedPosts(): Promise<Array<Post>>;
    getFriendRequests(): Promise<Array<FriendRequest>>;
    getNotifications(): Promise<Array<Notification>>;
    getPendingWithdrawals(): Promise<Array<Withdrawal>>;
    getPost(postId: bigint): Promise<Post | null>;
    getUserPosts(user: Principal): Promise<Array<Post>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSuggestions(): Promise<Array<Principal>>;
    getWalletBalance(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    likePost(postId: bigint): Promise<void>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    rejectFriendRequest(requestId: bigint): Promise<void>;
    rejectWithdrawal(withdrawalId: bigint): Promise<void>;
    requestWithdrawal(amount: bigint, method: WithdrawalMethod): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePost(postId: bigint): Promise<void>;
    sendFriendRequest(to: Principal): Promise<bigint>;
    sharePost(postId: bigint): Promise<void>;
    trackAdView(adId: bigint): Promise<void>;
    unbanUser(user: Principal): Promise<void>;
    unfollowUser(userToUnfollow: Principal): Promise<void>;
    unlikePost(postId: bigint): Promise<void>;
    unsavePost(postId: bigint): Promise<void>;
    updateEarningRate(newRate: bigint): Promise<void>;
    updateProfilePicture(storageKey: string): Promise<void>;
    viewPost(postId: bigint): Promise<void>;
}
import type { Comment as _Comment, FriendRequest as _FriendRequest, FriendRequestStatus as _FriendRequestStatus, Notification as _Notification, NotificationType as _NotificationType, Post as _Post, PostType as _PostType, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, Withdrawal as _Withdrawal, WithdrawalMethod as _WithdrawalMethod, WithdrawalStatus as _WithdrawalStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptFriendRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async approveWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async createAd(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAd(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAd(arg0, arg1, arg2);
            return result;
        }
    }
    async createPost(arg0: string, arg1: string, arg2: PostType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, to_candid_PostType_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, to_candid_PostType_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createUserProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getAdminStats(): Promise<{
        totalEarningsPaid: bigint;
        totalUsers: bigint;
        totalPosts: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAds(): Promise<Array<Ad>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAds();
            return result;
        }
    }
    async getAllWithdrawals(): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawals();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawals();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedPosts();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedPosts();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendRequests(): Promise<Array<FriendRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequests();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequests();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingWithdrawals(): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingWithdrawals();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingWithdrawals();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: bigint): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPosts(arg0: Principal): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPosts(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPosts(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSuggestions(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSuggestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSuggestions();
            return result;
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async rejectFriendRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFriendRequest(arg0);
            return result;
        }
    }
    async rejectWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: bigint, arg1: WithdrawalMethod): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawalMethod_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawalMethod_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async savePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePost(arg0);
            return result;
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async sharePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sharePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sharePost(arg0);
            return result;
        }
    }
    async trackAdView(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackAdView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackAdView(arg0);
            return result;
        }
    }
    async unbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async unsavePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsavePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsavePost(arg0);
            return result;
        }
    }
    async updateEarningRate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEarningRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEarningRate(arg0);
            return result;
        }
    }
    async updateProfilePicture(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePicture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePicture(arg0);
            return result;
        }
    }
    async viewPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.viewPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewPost(arg0);
            return result;
        }
    }
}
function from_candid_Comment_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_FriendRequestStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequestStatus): FriendRequestStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_FriendRequest_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequest): FriendRequest {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PostType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostType): PostType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalMethod_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalMethod): WithdrawalMethod {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Withdrawal_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Withdrawal): Withdrawal {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _WithdrawalStatus;
    method: _WithdrawalMethod;
    user: Principal;
    timestamp: bigint;
    amount: bigint;
}): {
    id: bigint;
    status: WithdrawalStatus;
    method: WithdrawalMethod;
    user: Principal;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n15(_uploadFile, _downloadFile, value.status),
        method: from_candid_WithdrawalMethod_n17(_uploadFile, _downloadFile, value.method),
        user: value.user,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    name: string;
    role: _UserRole;
    totalEarnings: bigint;
    followers: Array<Principal>;
    following: Array<Principal>;
    profilePicture: [] | [string];
    walletBalance: bigint;
}): {
    bio: string;
    username: string;
    name: string;
    role: UserRole;
    totalEarnings: bigint;
    followers: Array<Principal>;
    following: Array<Principal>;
    profilePicture?: string;
    walletBalance: bigint;
} {
    return {
        bio: value.bio,
        username: value.username,
        name: value.name,
        role: from_candid_UserRole_n22(_uploadFile, _downloadFile, value.role),
        totalEarnings: value.totalEarnings,
        followers: value.followers,
        following: value.following,
        profilePicture: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.profilePicture)),
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    postType: _PostType;
    shares: bigint;
    views: Array<Principal>;
    author: Principal;
    mediaUrl: string;
    likes: Array<Principal>;
    saves: Array<Principal>;
    timestamp: bigint;
    caption: string;
    comments: Array<_Comment>;
}): {
    id: bigint;
    postType: PostType;
    shares: bigint;
    views: Array<Principal>;
    author: Principal;
    mediaUrl: string;
    likes: Array<Principal>;
    saves: Array<Principal>;
    timestamp: bigint;
    caption: string;
    comments: Array<Comment>;
} {
    return {
        id: value.id,
        postType: from_candid_PostType_n30(_uploadFile, _downloadFile, value.postType),
        shares: value.shares,
        views: value.views,
        author: value.author,
        mediaUrl: value.mediaUrl,
        likes: value.likes,
        saves: value.saves,
        timestamp: value.timestamp,
        caption: value.caption,
        comments: from_candid_vec_n32(_uploadFile, _downloadFile, value.comments)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    author: Principal;
    timestamp: bigint;
    replies: Array<_Comment>;
}): {
    id: bigint;
    content: string;
    author: Principal;
    timestamp: bigint;
    replies: Array<Comment>;
} {
    return {
        id: value.id,
        content: value.content,
        author: value.author,
        timestamp: value.timestamp,
        replies: from_candid_vec_n32(_uploadFile, _downloadFile, value.replies)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: Principal;
    status: _FriendRequestStatus;
    from: Principal;
    timestamp: bigint;
}): {
    id: bigint;
    to: Principal;
    status: FriendRequestStatus;
    from: Principal;
    timestamp: bigint;
} {
    return {
        id: value.id,
        to: value.to,
        status: from_candid_FriendRequestStatus_n38(_uploadFile, _downloadFile, value.status),
        from: value.from,
        timestamp: value.timestamp
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notifType: _NotificationType;
    read: boolean;
    recipient: Principal;
    sender: Principal;
    message: string;
    timestamp: bigint;
    postId: [] | [bigint];
}): {
    id: bigint;
    notifType: NotificationType;
    read: boolean;
    recipient: Principal;
    sender: Principal;
    message: string;
    timestamp: bigint;
    postId?: bigint;
} {
    return {
        id: value.id,
        notifType: from_candid_NotificationType_n43(_uploadFile, _downloadFile, value.notifType),
        read: value.read,
        recipient: value.recipient,
        sender: value.sender,
        message: value.message,
        timestamp: value.timestamp,
        postId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.postId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "approved" in value ? WithdrawalStatus.approved : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: string;
} | {
    bank: {
        ifsc: string;
        accountNumber: string;
    };
}): {
    __kind__: "upi";
    upi: string;
} | {
    __kind__: "bank";
    bank: {
        ifsc: string;
        accountNumber: string;
    };
} {
    return "upi" in value ? {
        __kind__: "upi",
        upi: value.upi
    } : "bank" in value ? {
        __kind__: "bank",
        bank: value.bank
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    reel: null;
} | {
    image: null;
}): PostType {
    return "video" in value ? PostType.video : "reel" in value ? PostType.reel : "image" in value ? PostType.image : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): FriendRequestStatus {
    return "pending" in value ? FriendRequestStatus.pending : "rejected" in value ? FriendRequestStatus.rejected : "accepted" in value ? FriendRequestStatus.accepted : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like: null;
} | {
    comment: null;
} | {
    friendRequest: null;
} | {
    follow: null;
}): NotificationType {
    return "like" in value ? NotificationType.like : "comment" in value ? NotificationType.comment : "friendRequest" in value ? NotificationType.friendRequest : "follow" in value ? NotificationType.follow : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Withdrawal>): Array<Withdrawal> {
    return value.map((x)=>from_candid_Withdrawal_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendRequest>): Array<FriendRequest> {
    return value.map((x)=>from_candid_FriendRequest_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n41(_uploadFile, _downloadFile, x));
}
function to_candid_PostType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): _PostType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalMethod_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): _WithdrawalMethod {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    name: string;
    role: UserRole;
    totalEarnings: bigint;
    followers: Array<Principal>;
    following: Array<Principal>;
    profilePicture?: string;
    walletBalance: bigint;
}): {
    bio: string;
    username: string;
    name: string;
    role: _UserRole;
    totalEarnings: bigint;
    followers: Array<Principal>;
    following: Array<Principal>;
    profilePicture: [] | [string];
    walletBalance: bigint;
} {
    return {
        bio: value.bio,
        username: value.username,
        name: value.name,
        role: to_candid_UserRole_n50(_uploadFile, _downloadFile, value.role),
        totalEarnings: value.totalEarnings,
        followers: value.followers,
        following: value.following,
        profilePicture: value.profilePicture ? candid_some(value.profilePicture) : candid_none(),
        walletBalance: value.walletBalance
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): {
    video: null;
} | {
    reel: null;
} | {
    image: null;
} {
    return value == PostType.video ? {
        video: null
    } : value == PostType.reel ? {
        reel: null
    } : value == PostType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "upi";
    upi: string;
} | {
    __kind__: "bank";
    bank: {
        ifsc: string;
        accountNumber: string;
    };
}): {
    upi: string;
} | {
    bank: {
        ifsc: string;
        accountNumber: string;
    };
} {
    return value.__kind__ === "upi" ? {
        upi: value.upi
    } : value.__kind__ === "bank" ? {
        bank: value.bank
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
